### Numpy

In [23]:
import numpy as np 
import sys
import time

# consumes less memory
l1 = range(1000)
print(sys.getsizeof(5)*len(l1))

a1 = np.arange(1000)
print(a1.size*a1.itemsize)


28000
4000


In [24]:
SIZE = 1000000

l1 = range(SIZE)
l2 = range(SIZE)

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("List Execution Time:",(time.time()-start)*1000)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

start = time.time()
result = a1 + a2 # convinient to use
# faster execution time
print("Numpy Array Execution Time:",(time.time()-start)*1000)

List Execution Time: 137.00366020202637
Numpy Array Execution Time: 13.483762741088867


In [63]:
a = np.arange(5)

# b = a # when copying a numpy array use .copy() else it will also change original values 
b = a.copy()

print(a)
print(b)

b[0] = 10

print(a) 
print(b)

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[10  1  2  3  4]


#### Numpy Basic Operations

In [25]:
# a = np.array([9,6,3,5,4,3]) # 1D array

a = np.array([[9,6], [3,5], [4,3]]) # 2D array 

print("a[2]: ", a[2]) 
print("a[2][0]: ", a[2][0]) 
print("Dimension:", np.ndim(a)) # dimension of array
print("Itemsize:", a.itemsize) # size of each element in array
print("Size:", a.size) # no. of elements in array (across all the dimensions)
print("Shape:", a.shape) # (height, width)


a[2]:  [4 3]
a[2][0]:  4
Dimension: 2
Itemsize: 4
Size: 6
Shape: (3, 2)


In [26]:
a = np.zeros((3,6)) # array of given dimension containing zeroes of float64 type
# a = np.ones((4,3)) # similary ones are initialized

print(a)
print("dtype:",a.dtype) # gives datatype of items in array

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
dtype: float64


In [27]:
# np.arange(5) # similar to range()
np.arange(1,5,2) # (start, end, commen difference)

array([1, 3])

In [28]:
# gives an array that equally distributes to start and end in given no. of subparts
np.linspace(1,5,10) # (start, end, no. of subparts)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [29]:
a = np.array([[1,2],[3,4],[5,6]])

# print(a)
# print(a.shape)

# reshaping array height*width should be equal
# print(a.reshape(2,3))
# print(a.reshape(1,6))
print(a.reshape(6,1))



[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [30]:
a = np.array([[1,2],[3,4],[5,6]])

print(a)
print(a.ravel()) # returns flatten array  

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [31]:
a = np.array([[1,2],[3,4],[5,6]])

print("Min:", a.min())
print("Max:", a.max())
print("Sum:", a.sum())
print("Sum, axis=0:", a.sum(axis=0)) # along y-axis
print("Sum, axis=1:", a.sum(axis=1)) # along x-axis
print("Sum:", a.sum())
print("Mean:", a.mean())
print("Standard Deviation:", a.std())
print("Square Root of Array:\n", np.sqrt(a))

Min: 1
Max: 6
Sum: 21
Sum, axis=0: [ 9 12]
Sum, axis=1: [ 3  7 11]
Sum: 21
Mean: 3.5
Standard Deviation: 1.707825127659933
Square Root of Array:
 [[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [32]:
a = np.array([[1,2],[3,4]])
b = np.array([[9,8],[7,6]])

# print(a)
# print(b)
# print(a+b)
# print(a-b)
# print(a*b)
# print(a/b)
# print(a//b)
# print(a%b)
print(a.dot(b)) # dot product (rowXcolumn)

[[23 20]
 [55 48]]


In [33]:
arr = np.array([1,2,3,5,4,6])

# print(arr[0])
print(arr[0:2]) # slicing
print(arr[-2]) # negative indexing

[1 2]
4


In [34]:
a = np.array([[1,3,5],
              [4,8,1],
              [6,2,7]])

# (rwo, column)
print("0th row and 2nd column:", a[0,2]) # a[0][2]
print("0th & 1st row, 2nd column:", a[0:2,2]) # IMP, because a[0:2][2] => ERROR
print("0th row, 1st & 2nd column:", a[0][1:])
print("1th & 2nd column:\n",a[:,0:2])
print("2nd row:", a[-1])

0th row and 2nd column: 5
0th & 1st row, 2nd column: [5 1]
0th row, 1st & 2nd column: [3 5]
1th & 2nd column:
 [[1 3]
 [4 8]
 [6 2]]
2nd row: [6 2 7]


In [39]:
a = np.array([[1,3,5],
              [4,8,1],
              [6,2,7]])

# Iterating through the array
for row in a:
    print(row)

for cell in a.flat: # row X column
    print(cell)

[1 3 5]
[4 8 1]
[6 2 7]
1
3
5
4
8
1
6
2
7


In [43]:
# Stacking in Numpy
a = np.arange(0,6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

print("a:", a)
print("b:", b)

print("Vertical Stacking: ")
print(np.vstack((a,b)))

print("Horizontal Stacking: ")
print(np.hstack((a,b)))

a: [[0 1]
 [2 3]
 [4 5]]
b: [[ 6  7]
 [ 8  9]
 [10 11]]
Vertical Stacking: 
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
Horizontal Stacking: 
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [56]:
# Splitting in Numpy
a = np.arange(30).reshape(2,15)
print(a)

# vertical split
result = np.vsplit(a,2)
print(result[0])
print(result[1])

# horizontal spilt
result = np.hsplit(a,5)
print(result[0])
print(result[1])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[ 0  1  2]
 [15 16 17]]
[[ 3  4  5]
 [18 19 20]]


In [61]:
a = np.arange(12).reshape(3,4)
print(a)

# boolean array that stores result for each cell in array
b = a > 4
print(b)

# print(a[b])
a[b] = -2

print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[[ 0  1  2  3]
 [ 4 -2 -2 -2]
 [-2 -2 -2 -2]]
